#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

TOPDIR=$(pwd)
GIT_FLAGS="${GIT_FLAGS:=-q}"
HK_GIT="https://github.com/hardkernel/u-boot"

usage() {
  echo "$0 XU3|U2|C1|C2"
  echo "  ex. $0 XU3"
  exit 1
}

sources() {
  echo -n "Getting Sources ... "

  cd $TOPDIR

  if [ ! -d hk-bootloader.git ]; then
    git clone $GIT_FLAGS $HK_GIT hk-bootloader.git
  fi

  cd $TOPDIR/hk-bootloader.git

  git reset $GIT_FLAGS --hard
  git clean $GIT_FLAGS -fd

  git checkout $GIT_FLAGS -m $BRANCH

  git pull $GIT_FLAGS

  if [ -n $2 ]; then
    git reset $GIT_FLAGS --hard $2
    git clean $GIT_FLAGS -fd
  fi

  GIT_REV=`git log -n1 --format=%h`
  sed -i "s|^EXTRAVERSION[[:space:]]*=.*$|EXTRAVERSION = +$GIT_REV|" Makefile
  VERSION="$(grep \^VERSION Makefile | head -1 | awk '{print $3}').$(grep \^PATCHLEVEL Makefile | awk '{print $3}')+$GIT_REV"

  echo "DONE"
}

package() {
  cd $TOPDIR

  if [ -d u-boot-$VERSION ]; then
    echo -n "Cleaning Old Release ... "
    rm -rf u-boot-$VERSION
    echo "DONE"
  fi

  echo -n "Copying GIT to Release ... "
  cp -a hk-bootloader.git u-boot-$VERSION
  echo "DONE"

  echo -n "Cleaning Source ... "
  rm -rf u-boot-$VERSION/.git
  echo "DONE"

  echo -n "Compressing Source ... "
  tar cJf u-boot-$VERSION.tar.xz u-boot-$VERSION
  echo "DONE"

  echo -n "Final Cleanup ... "
  rm -rf u-boot-$VERSION
  echo "DONE"
}

if [ -z $1 ]; then
  usage
else
  case $1 in
    U2|u2|U3|u3) BRANCH="odroid-v2010.12"    ; BUILD=U2  ;;
    XU3|xu3)     BRANCH="odroidxu3-v2012.07" ; BUILD=XU3 ;;
    C1|c1)       BRANCH="odroidc-v2011.03"   ; BUILD=C1  ;;
    C2|c2)       BRANCH="odroidc2-v2015.01"  ; BUILD=C2  ;;
  esac
  sources $1 $2
  package $1
fi
